repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-linter
        name: Ruff linter
        entry: poetry run ruff check . --fix
        language: system
        pass_filenames: false
        types:
          - python

      - id: ruff-format
        name: Ruff formatter
        entry: poetry run ruff format .
        language: system
        pass_filenames: false
        types:
          - python

      - id: run-pytest
        name: Run tests
        entry: make test
        language: system
        types:
          - python
